insert into tacgia (id, tenTacGia) values (1, 'Carvedilol');
insert into tacgia (id, tenTacGia) values (2, 'AcipHex');
insert into tacgia (id, tenTacGia) values (3, 'ZALTRAP');
insert into tacgia (id, tenTacGia) values (4, 'Wilate - von Willebrand Factor/Coagulation Factor VIII Complex (Human)');
insert into tacgia (id, tenTacGia) values (5, 'MENEST');
insert into tacgia (id, tenTacGia) values (6, 'EROS EXTENDED LOVE GLIDE');
insert into tacgia (id, tenTacGia) values (7, 'Lysol');
insert into tacgia (id, tenTacGia) values (8, 'Lanolin');
insert into tacgia (id, tenTacGia) values (9, 'Betamethasone Dipropionate');
insert into tacgia (id, tenTacGia) values (10, 'topcare arthritis pain');
insert into tacgia (id, tenTacGia) values (11, 'Smart Sense All Day Allergy D');
insert into tacgia (id, tenTacGia) values (12, 'Promethazine Hydrochloride');
insert into tacgia (id, tenTacGia) values (13, 'Ranexa');
insert into tacgia (id, tenTacGia) values (14, 'MAX HYALURONIC FORMULA AMPOULE');
insert into tacgia (id, tenTacGia) values (15, 'mitoXANTRONE');
insert into tacgia (id, tenTacGia) values (16, 'Paroxetine');
insert into tacgia (id, tenTacGia) values (17, 'Daily Moisturizing');
insert into tacgia (id, tenTacGia) values (18, 'Koh Gen Do Aqua Foundation');
insert into tacgia (id, tenTacGia) values (19, 'Oratox');
insert into tacgia (id, tenTacGia) values (20, 'MORPHINE SULFATE');
insert into tacgia (id, tenTacGia) values (21, 'Cor Aurum 17/10');
insert into tacgia (id, tenTacGia) values (22, 'English Walnut');
insert into tacgia (id, tenTacGia) values (23, 'Lamivudine and Zidovudine');
insert into tacgia (id, tenTacGia) values (24, 'EZ-Detox Super Drainage Formula');
insert into tacgia (id, tenTacGia) values (25, 'Potassium Chloride');
insert into tacgia (id, tenTacGia) values (26, 'Quetiapine Fumarate');
insert into tacgia (id, tenTacGia) values (27, 'nighttime sleep aid');
insert into tacgia (id, tenTacGia) values (28, 'Aliclen');
insert into tacgia (id, tenTacGia) values (29, 'CTx4 Gel 1100');
insert into tacgia (id, tenTacGia) values (30, 'Aspirin');
insert into tacgia (id, tenTacGia) values (31, 'Levaquin');
insert into tacgia (id, tenTacGia) values (32, 'Bacitracin Zinc');
insert into tacgia (id, tenTacGia) values (33, 'Palgic');
insert into tacgia (id, tenTacGia) values (34, 'Dextran 75');
insert into tacgia (id, tenTacGia) values (35, 'CD CAPTURE TOTALE Triple Correcting Serum Dark Spots-Radiance with sunscreen Broad Spectrum SPF 25 010');
insert into tacgia (id, tenTacGia) values (36, 'milk of magnesia');
insert into tacgia (id, tenTacGia) values (37, 'Doxycycline Hyclate');
insert into tacgia (id, tenTacGia) values (38, 'Caverject');
insert into tacgia (id, tenTacGia) values (39, 'Lamotrigine');
insert into tacgia (id, tenTacGia) values (40, 'Etodolac');
insert into tacgia (id, tenTacGia) values (41, 'Liver Complex');
insert into tacgia (id, tenTacGia) values (42, 'Theochem White Tea Hand and Body Wash');
insert into tacgia (id, tenTacGia) values (43, 'Nadolol');
insert into tacgia (id, tenTacGia) values (44, 'Atorvastatin Calcium');
insert into tacgia (id, tenTacGia) values (45, 'NovoLog');
insert into tacgia (id, tenTacGia) values (46, 'Ceftriaxone');
insert into tacgia (id, tenTacGia) values (47, 'CV Medicated');
insert into tacgia (id, tenTacGia) values (48, 'Bronchitis-Asthma');
insert into tacgia (id, tenTacGia) values (49, 'Diazepam');
insert into tacgia (id, tenTacGia) values (50, 'Acetaminophen PM');
insert into tacgia (id, tenTacGia) values (51, 'Isolyte S');
insert into tacgia (id, tenTacGia) values (52, 'Risperidone');
insert into tacgia (id, tenTacGia) values (53, 'Sun Diffusing Protector');
insert into tacgia (id, tenTacGia) values (54, 'Verapamil Hydrochloride');
insert into tacgia (id, tenTacGia) values (55, 'METHOTREXATE');
insert into tacgia (id, tenTacGia) values (56, 'CASEIN');
insert into tacgia (id, tenTacGia) values (57, 'POVIDONE IODINE SWABSTICS ANTISEPTIC GERMICIDE');
insert into tacgia (id, tenTacGia) values (58, 'Amoxicillin');
insert into tacgia (id, tenTacGia) values (59, 'Methimazole');
insert into tacgia (id, tenTacGia) values (60, 'Dorzolamide Hydrochloride');
insert into tacgia (id, tenTacGia) values (61, 'PAROXETINE');
insert into tacgia (id, tenTacGia) values (62, 'ProClearz');
insert into tacgia (id, tenTacGia) values (63, 'Dove Ultimate Go Fresh Energizing');
insert into tacgia (id, tenTacGia) values (64, 'Erythrocin Stearate');
insert into tacgia (id, tenTacGia) values (65, 'Fenoprofen');
insert into tacgia (id, tenTacGia) values (66, 'Potassium Chloride');
insert into tacgia (id, tenTacGia) values (67, 'Primaquine Phosphate');
insert into tacgia (id, tenTacGia) values (68, 'ESIKA');
insert into tacgia (id, tenTacGia) values (69, 'Night Time');
insert into tacgia (id, tenTacGia) values (70, 'Piperacillin and Tazobactam');
insert into tacgia (id, tenTacGia) values (71, 'Lightening Day Cream');
insert into tacgia (id, tenTacGia) values (72, 'Severe Sinus Congestion and Pain');
insert into tacgia (id, tenTacGia) values (73, 'Neomycin and Polymyxin B Sulfates and Hydrocortisone');
insert into tacgia (id, tenTacGia) values (74, 'Ropinirole Hydrochloride');
insert into tacgia (id, tenTacGia) values (75, 'Sleep aid');
insert into tacgia (id, tenTacGia) values (76, 'Shopko');
insert into tacgia (id, tenTacGia) values (77, 'OP Dark Tanning Xtreme Oil Amplifier SPF4');
insert into tacgia (id, tenTacGia) values (78, 'Kogenate FS');
insert into tacgia (id, tenTacGia) values (79, 'Cephalexin');
insert into tacgia (id, tenTacGia) values (80, 'Doxycycline Hyclate');
insert into tacgia (id, tenTacGia) values (81, 'TheraTears');
insert into tacgia (id, tenTacGia) values (82, 'Buspirone Hydrochloride');
insert into tacgia (id, tenTacGia) values (83, 'Diltiazem Hydrochloride');
insert into tacgia (id, tenTacGia) values (84, 'Mastic Dent Oulo Action');
insert into tacgia (id, tenTacGia) values (85, 'FoamFresh Alco-Foam Hand Sanitizer');
insert into tacgia (id, tenTacGia) values (86, 'Secura Moisturizing Cleanser');
insert into tacgia (id, tenTacGia) values (87, 'kaiser permanente benzoyl peroxide');
insert into tacgia (id, tenTacGia) values (88, 'D.H.E. 45');
insert into tacgia (id, tenTacGia) values (89, 'Etomidate');
insert into tacgia (id, tenTacGia) values (90, 'Irbesartan and Hydrochlorothiazide');
insert into tacgia (id, tenTacGia) values (91, 'Tamiflu');
insert into tacgia (id, tenTacGia) values (92, 'Tretinoin');
insert into tacgia (id, tenTacGia) values (93, 'Hydrocodone Bitartrate And Acetaminophen');
insert into tacgia (id, tenTacGia) values (94, 'Sodium Iodide I 123');
insert into tacgia (id, tenTacGia) values (95, 'Acremonium strictum');
insert into tacgia (id, tenTacGia) values (96, 'Kit for the Preparation of Technetium Tc99m Sestamibi');
insert into tacgia (id, tenTacGia) values (97, 'ALAVERT ALLERGY SINUS D-12');
insert into tacgia (id, tenTacGia) values (98, 'Nutrilyte');


insert into sach (id, tenSach, namXuatBan, idTacGia) values (1, 'POU', 2002, 1);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (2, 'BNB', 2012, 2);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (3, 'TYF', 2003, 3);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (4, 'BDO', 2007, 4);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (5, 'IXP', 2000, 5);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (6, 'MVA', 1997, 6);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (7, 'AXJ', 2013, 7);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (8, 'LBK', 1993, 8);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (9, 'CDQ', 1996, 9);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (10, 'YHR', 1993, 10);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (11, 'MDZ', 2013, 11);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (12, 'KNI', 1984, 12);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (13, 'JDN', 1986, 13);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (14, 'CRX', 2006, 14);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (15, 'DPU', 1985, 15);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (16, 'YGZ', 1988, 16);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (17, 'PGH', 2009, 17);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (18, 'HFT', 2000, 18);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (19, 'BUJ', 1990, 19);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (20, 'VIY', 1995, 20);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (21, 'DCF', 2004, 21);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (22, 'GDI', 2007, 22);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (23, 'MRA', 1997, 23);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (24, 'TTH', 2005, 24);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (25, 'ASJ', 2012, 25);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (26, 'NEJ', 1999, 26);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (27, 'SOR', 2005, 27);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (28, 'OTD', 2011, 28);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (29, 'LUU', 1997, 29);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (30, 'MMU', 2007, 30);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (31, 'KLB', 2004, 31);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (32, 'SXA', 2000, 32);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (33, 'KGE', 2007, 33);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (34, 'MJS', 2008, 34);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (35, 'AAC', 2005, 35);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (36, 'DPE', 2007, 36);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (37, 'MNX', 2010, 37);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (38, 'ODH', 2007, 38);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (39, 'BXO', 2010, 39);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (40, 'HOO', 1993, 40);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (41, 'UDA', 2012, 41);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (42, 'YNM', 1977, 42);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (43, 'CAP', 2004, 43);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (44, 'LMZ', 2001, 44);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (45, 'SVV', 2004, 45);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (46, 'CAG', 2011, 46);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (47, 'UZR', 2006, 47);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (48, 'TBS', 2010, 48);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (49, 'UMU', 2005, 49);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (50, 'INF', 2008, 50);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (51, 'YYG', 2004, 51);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (52, 'GYP', 2005, 52);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (53, 'PVA', 2008, 53);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (54, 'CRP', 2007, 54);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (55, 'TPU', 1985, 55);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (56, 'ALN', 2002, 56);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (57, 'XLU', 1995, 57);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (58, 'NTC', 1996, 58);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (59, 'YTX', 1995, 59);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (60, 'MCY', 2005, 60);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (61, 'CPF', 1994, 61);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (62, 'ISW', 1993, 62);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (63, 'LMS', 2004, 63);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (64, 'YHO', 1996, 64);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (65, 'YHM', 1995, 65);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (66, 'AEH', 2005, 66);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (67, 'ENU', 2010, 67);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (68, 'CHH', 2008, 68);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (69, 'BVI', 2004, 69);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (70, 'ATQ', 2001, 70);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (71, 'GKH', 1996, 71);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (72, 'IKP', 2002, 72);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (73, 'JSU', 2011, 73);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (74, 'JRA', 1991, 74);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (75, 'JNG', 2000, 75);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (76, 'OSC', 2003, 76);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (77, 'FAO', 2004, 77);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (78, 'QID', 1993, 78);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (79, 'HTU', 2000, 79);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (80, 'FRG', 1999, 80);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (81, 'MOG', 2006, 81);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (82, 'MNJ', 2004, 82);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (83, 'ISJ', 1997, 83);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (84, 'SZE', 2003, 84);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (85, 'PLM', 2004, 85);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (86, 'YIC', 1998, 86);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (87, 'KRX', 1994, 87);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (88, 'KAE', 2009, 88);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (89, 'TNM', 2012, 89);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (90, 'HYR', 1969, 90);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (91, 'HWN', 1997, 91);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (92, 'JEJ', 2011, 92);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (93, 'YMT', 2005, 93);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (94, 'AKD', 1992, 94);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (95, 'KDK', 1995, 95);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (96, 'TJU', 1992, 96);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (97, 'RSA', 1996, 97);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (98, 'JUL', 2000, 98);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (99, 'JST', 1993, 99);
insert into sach (id, tenSach, namXuatBan, idTacGia) values (100, 'OCC', 1992, 100);